### ISSUE TITLE
app.use(jsonBody({ limit: '100kb' }));  -- not working

### ISSUE THREAD

**Issue by robotnic** [venables/koa-json-body#3]
I get following error

assert.js:86
  throw new assert.AssertionError({
        ^
AssertionError: app.use() requires a generator function
    at Application.app.use (C:\Users\A6102.PAD01\projects\proxy2\node_modules\koa\lib\application.js:103:5)
    at Namespace.<anonymous> (C:\Users\A6102.PAD01\projects\proxy2\index.js:29:9)
    at Namespace.emit (events.js:107:17)
    at Namespace.emit (C:\Users\A6102.PAD01\projects\proxy2\node_modules\socket.io\lib\namespace.js:205:10)
    at C:\Users\A6102.PAD01\projects\proxy2\node_modules\socket.io\lib\namespace.js:172:14
    at process._tickCallback (node.js:355:11)

**Comment by venables** [comment]
@robotnic how are you requiring the module? can you post your entire file?
